import Link from 'next/link';
import { apiGet, type AdminOverview, type Provider } from '@/lib/api';
import { hasAdminSession } from '@/lib/admin-session';
import { logoutAdmin, moderateProvider } from './actions';
import { redirect } from 'next/navigation';

export const dynamic = 'force-dynamic';

export default async function AdminPage() {
  if (!await hasAdminSession()) redirect('/admin/login');
  const [overviewResult, providersResult] = await Promise.allSettled([apiGet<AdminOverview>('/api/admin/overview', { admin: true }), apiGet<Provider[]>('/api/admin/providers', { admin: true })]);
  const overview = overviewResult.status === 'fulfilled' ? overviewResult.value : null;
  const providers = providersResult.status === 'fulfilled' ? providersResult.value : [];
  const pendingProviders = providers.filter((provider) => provider.status === 'PENDING');
  return <section><div className="sectionHead"><div><span className="eyebrow">إدارة هنا قنا</span><h1 className="pageTitle">لوحة المتابعة</h1></div><form action={logoutAdmin}><button className="secondaryButton" type="submit">خروج</button></form></div><p className="pageLead">منصة Next.js متصلة بـ API التطبيق نفسه. مفاتيح الإدارة تبقى في الخادم ولا تصل للمتصفح.</p><div className="adminLayout">{[{ label: 'مقدمو خدمة نشطون', value: overview?.providers }, { label: 'بانتظار مراجعة', value: overview?.pending }, { label: 'إعلانات رئيسية نشطة', value: overview?.listings }, { label: 'تقييمات هذا الشهر', value: overview?.reviews }].map((stat) => <article className="surface stat" key={stat.label}><small>{stat.label}</small><strong>{stat.value ?? '—'}</strong><span>{overview ? 'بيانات مباشرة' : 'تحقق من مفتاح الإدارة'}</span></article>)}</div><section className="section surface table"><div className="sectionHead" style={{ padding: '18px 18px 0' }}><h2>طلبات النشاط بانتظار المراجعة</h2><span className="badge">{pendingProviders.length}</span></div>{pendingProviders.length === 0 ? <p className="empty">لا توجد طلبات معلّقة الآن.</p> : <table><thead><tr><th>النشاط</th><th>الفئة</th><th>المنطقة</th><th>القرار</th></tr></thead><tbody>{pendingProviders.map((provider) => <tr key={provider.id}><td>{provider.name}</td><td>{provider.categories[0]?.category.name ?? '—'}</td><td>{provider.area.name}</td><td><div className="actionRow"><form action={moderateProvider}><input type="hidden" name="id" value={provider.id} /><input type="hidden" name="status" value="APPROVED" /><button className="approveButton" type="submit">اعتماد</button></form><form action={moderateProvider}><input type="hidden" name="id" value={provider.id} /><input type="hidden" name="status" value="REJECTED" /><button className="rejectButton" type="submit">رفض</button></form></div></td></tr>)}</tbody></table>}</section><section className="section surface table"><div className="sectionHead" style={{ padding: '18px 18px 0' }}><h2>كل مقدمي الخدمات</h2><Link href="/providers">عرض الدليل</Link></div><table><thead><tr><th>النشاط</th><th>الفئة</th><th>المنطقة</th><th>الحالة</th></tr></thead><tbody>{providers.slice(0, 10).map((provider) => <tr key={provider.id}><td>{provider.name}</td><td>{provider.categories[0]?.category.name ?? '—'}</td><td>{provider.area.name}</td><td><span className="badge">{provider.status === 'APPROVED' ? 'منشور' : provider.status === 'PENDING' ? 'قيد المراجعة' : 'مرفوض'}</span></td></tr>)}</tbody></table></section></section>;
}
