import Link from 'next/link';
import { redirect } from 'next/navigation';
import { apiGet } from '@/lib/api';
import { hasAdminSession } from '@/lib/admin-session';
import { createNow, moderateNow, updateNow } from '../actions';

export const dynamic = 'force-dynamic';
type NowItem = { id: string; title: string; body?: string | null; category: string; status: string; area?: { id: string; name: string } | null; startsAt: string; endsAt?: string | null };
type Area = { id: string; name: string };
type Constant = { id: string; name: string };

export default async function NowAdminPage() {
  if (!await hasAdminSession()) redirect('/admin/login');
  const [items, areasResult, typesResult] = await Promise.all([apiGet<NowItem[]>('/api/admin/now', { admin: true }).catch(() => []), apiGet<{ data: Area[] }>('/api/areas', { cache: 'no-store' }).catch(() => ({ data: [] })), apiGet<{ data: Constant[] }>('/api/constants/news-types', { cache: 'no-store' }).catch(() => ({ data: [{ id: 'fallback-general', name: 'عام' }] }))]);
  const types = typesResult.data.length ? typesResult.data : [{ id: 'fallback-general', name: 'عام' }];
  const categoryOptions = (selected?: string) => <>{types.map((type) => <option key={type.id} value={type.name}>{type.name}</option>)}{selected && !types.some((type) => type.name === selected) && <option value={selected}>{selected}</option>}</>;
  return <section><div className="sectionHead"><div><span className="eyebrow">المحتوى المحلي</span><h1 className="pageTitle">إدارة «دلوقتي»</h1></div><Link href="/admin">العودة للوحة</Link></div><p className="pageLead">انشر تنبيهات وفعاليات وافتتاحات مرتبطة بقنا أو بمنطقة محددة، مع جدولة كاملة للظهور والانتهاء.</p><form action={createNow} className="surface formGrid"><label>العنوان<input name="title" required /></label><label>التصنيف<select name="category" defaultValue={types[0].name}>{categoryOptions()}</select></label><label>المنطقة<select name="areaId" defaultValue=""><option value="">كل قنا</option>{areasResult.data.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select></label><label>يبدأ<input name="startsAt" type="datetime-local" /></label><label>ينتهي<input name="endsAt" type="datetime-local" /></label><label className="wideField">التفاصيل<textarea name="body" maxLength={600} /></label><button className="primaryButton" type="submit">نشر التحديث</button></form><section className="section surface table"><div className="sectionHead" style={{ padding: '18px 18px 0' }}><h2>التحديثات المنشورة</h2><span className="badge">{items.length}</span></div><table><thead><tr><th>التعديل</th><th>المنطقة/الفترة</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><form action={updateNow} className="compactForm"><input type="hidden" name="id" value={item.id} /><input name="title" defaultValue={item.title} required /><select name="category" defaultValue={item.category}>{categoryOptions(item.category)}</select><textarea name="body" defaultValue={item.body ?? ''} /><select name="areaId" defaultValue={item.area?.id ?? ''}><option value="">كل قنا</option>{areasResult.data.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select><input name="startsAt" type="datetime-local" defaultValue={item.startsAt ? item.startsAt.slice(0, 16) : ''} /><input name="endsAt" type="datetime-local" defaultValue={item.endsAt ? item.endsAt.slice(0, 16) : ''} /><select name="status" defaultValue={item.status}><option value="APPROVED">منشور</option><option value="REJECTED">مخفي</option></select><button className="secondaryButton" type="submit">حفظ</button></form></td><td>{item.area?.name ?? 'كل قنا'}<small>{item.endsAt ? `ينتهي ${new Date(item.endsAt).toLocaleString('ar-EG')}` : 'بدون انتهاء'}</small></td><td><span className="badge">{item.status}</span></td><td>{item.status === 'PENDING' && <div className="actionRow"><form action={moderateNow}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="status" value="APPROVED" /><button className="approveButton" type="submit">اعتماد</button></form><form action={moderateNow}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="status" value="REJECTED" /><button className="rejectButton" type="submit">رفض</button></form></div>}</td></tr>)}</tbody></table></section></section>;
}
