import Link from 'next/link';
import { redirect } from 'next/navigation';
import { apiGet } from '@/lib/api';
import { hasAdminSession } from '@/lib/admin-session';
import { createOfferAdmin, createServiceAdmin, moderateOffer, moderateService, updateLifecycle, updateOfferAdmin, updateServiceAdmin } from '../actions';

export const dynamic = 'force-dynamic';
type Provider = { id: string; name: string };
type Service = { id: string; name: string; description?: string | null; logoUrl?: string | null; price?: string | number | null; priceNote?: string | null; status: string; provider: Provider };
type Offer = { id: string; title: string; description?: string | null; startsAt: string; endsAt: string; status: string; provider: Provider };

export default async function ServicesAdminPage() {
  if (!await hasAdminSession()) redirect('/admin/login');
  const [services, offers, providers] = await Promise.all([
    apiGet<Service[]>('/api/admin/services', { admin: true }).catch(() => []),
    apiGet<Offer[]>('/api/admin/offers', { admin: true }).catch(() => []),
    apiGet<Provider[]>('/api/admin/providers', { admin: true }).catch(() => []),
  ]);
  const providerOptions = () => providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.name}</option>);
  return <section><div className="sectionHead"><div><span className="eyebrow">محتوى الأنشطة</span><h1 className="pageTitle">الخدمات والعروض</h1></div><Link href="/admin">العودة للوحة</Link></div><p className="pageLead">إنشاء وتعديل وجدولة واعتماد كل خدمة أو عرض ظاهر داخل صفحة النشاط.</p>
    <div className="adminLayout"><form action={createServiceAdmin} className="surface formGrid"><h2 className="wideField">إضافة خدمة</h2><label>النشاط<select name="providerId" required>{providerOptions()}</select></label><label>اسم الخدمة<input name="name" required /></label><label>السعر<input name="price" type="number" min="0" step="0.01" /></label><label>ملاحظة السعر<input name="priceNote" /></label><label>رابط الشعار<input name="logoUrl" type="url" /></label><label className="wideField">الوصف<textarea name="description" /></label><button className="primaryButton wideField" type="submit">إضافة الخدمة ونشرها</button></form><form action={createOfferAdmin} className="surface formGrid"><h2 className="wideField">إضافة عرض</h2><label>النشاط<select name="providerId" required>{providerOptions()}</select></label><label>عنوان العرض<input name="title" required /></label><label>يبدأ<input name="startsAt" type="datetime-local" required /></label><label>ينتهي<input name="endsAt" type="datetime-local" required /></label><label className="wideField">الوصف<textarea name="description" /></label><button className="primaryButton wideField" type="submit">إضافة العرض ونشره</button></form></div>
    <section className="section surface table"><div className="sectionHead"><h2>الخدمات</h2><span className="badge">{services.length}</span></div><table><thead><tr><th>التعديل الكامل</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{services.map((item) => <tr key={item.id}><td><form action={updateServiceAdmin} className="compactForm"><input type="hidden" name="id" value={item.id}/><select name="providerId" defaultValue={item.provider.id}>{providerOptions()}</select><input name="name" defaultValue={item.name} required/><input name="price" type="number" min="0" step="0.01" defaultValue={item.price ?? ''}/><input name="priceNote" defaultValue={item.priceNote ?? ''} placeholder="ملاحظة السعر"/><input name="logoUrl" type="url" defaultValue={item.logoUrl ?? ''} placeholder="رابط الشعار"/><textarea name="description" defaultValue={item.description ?? ''}/><select name="status" defaultValue={item.status}><option value="APPROVED">منشور</option><option value="REJECTED">مخفي</option></select><button className="secondaryButton" type="submit">حفظ</button></form></td><td><span className="badge">{item.status}</span><small>{item.provider.name}</small></td><td><div className="actionRow">{item.status === 'PENDING' && <><form action={moderateService}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="status" value="APPROVED"/><button className="approveButton" type="submit">اعتماد</button></form><form action={moderateService}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="status" value="REJECTED"/><button className="rejectButton" type="submit">رفض</button></form></>}<form action={updateLifecycle}><input type="hidden" name="entity" value="service"/><input type="hidden" name="id" value={item.id}/><input type="hidden" name="action" value="ARCHIVE"/><input type="hidden" name="reason" value="أرشفة إدارية"/><button className="secondaryButton" type="submit">أرشفة</button></form></div></td></tr>)}</tbody></table></section>
    <section className="section surface table"><div className="sectionHead"><h2>العروض</h2><span className="badge">{offers.length}</span></div><table><thead><tr><th>التعديل الكامل</th><th>الفترة والحالة</th><th>إجراء</th></tr></thead><tbody>{offers.map((item) => <tr key={item.id}><td><form action={updateOfferAdmin} className="compactForm"><input type="hidden" name="id" value={item.id}/><select name="providerId" defaultValue={item.provider.id}>{providerOptions()}</select><input name="title" defaultValue={item.title} required/><input name="startsAt" type="datetime-local" defaultValue={item.startsAt.slice(0, 16)} required/><input name="endsAt" type="datetime-local" defaultValue={item.endsAt.slice(0, 16)} required/><textarea name="description" defaultValue={item.description ?? ''}/><select name="status" defaultValue={item.status}><option value="APPROVED">منشور</option><option value="REJECTED">مخفي</option></select><button className="secondaryButton" type="submit">حفظ</button></form></td><td>{new Date(item.startsAt).toLocaleDateString('ar-EG')} — {new Date(item.endsAt).toLocaleDateString('ar-EG')}<small>{item.provider.name} · {item.status}</small></td><td><div className="actionRow">{item.status === 'PENDING' && <><form action={moderateOffer}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="status" value="APPROVED"/><button className="approveButton" type="submit">اعتماد</button></form><form action={moderateOffer}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="status" value="REJECTED"/><button className="rejectButton" type="submit">رفض</button></form></>}<form action={updateLifecycle}><input type="hidden" name="entity" value="offer"/><input type="hidden" name="id" value={item.id}/><input type="hidden" name="action" value="ARCHIVE"/><input type="hidden" name="reason" value="أرشفة إدارية"/><button className="secondaryButton" type="submit">أرشفة</button></form></div></td></tr>)}</tbody></table></section>
  </section>;
}
