import { redirect } from 'next/navigation';
import { apiGet } from '@/lib/api';
import { hasAdminSession } from '@/lib/admin-session';
import { moderateMinShaterRecommendation, moderateMinShaterReport, moderateMinShaterRequest } from '../actions';

export const dynamic = 'force-dynamic';
type PageData<T> = { data: T[]; total: number };
type RequestItem = { id: string; title: string; description?: string | null; moderationStatus: string; status: string; createdAt: string; user?: { name: string; email?: string | null }; category?: { name: string }; area?: { name: string } | null; _count?: { recommendations: number } };
type RecommendationItem = { id: string; recommendedName?: string | null; description?: string | null; moderationStatus: string; createdAt: string; request?: { id: string; title: string; status: string }; provider?: { name: string } | null; user?: { name: string } };
type ReportItem = { id: string; reason: string; status: string; createdAt: string; request?: { title: string } | null; recommendation?: { recommendedName?: string | null; provider?: { name: string } | null } | null; reporter?: { name: string } };
type Analytics = { requests: number; pendingRequests: number; approvedRequests: number; closedRequests: number; recommendations: number; pendingRecommendations: number; reports: number; zeroRecommendation: number };

const statusLabel: Record<string, string> = { PENDING: 'معلّق', APPROVED: 'معتمد', REJECTED: 'مرفوض', ARCHIVED: 'مؤرشف', HIDDEN: 'مخفي', RESOLVED: 'تم الحل', DISMISSED: 'مستبعد' };

export default async function MinShaterAdminPage() {
  if (!await hasAdminSession()) redirect('/admin/login');
  const [requests, recommendations, reports, analytics] = await Promise.all([
    apiGet<PageData<RequestItem>>('/api/admin/min-shater/requests?page=1&pageSize=50', { admin: true }).catch(() => ({ data: [], total: 0 })),
    apiGet<PageData<RecommendationItem>>('/api/admin/min-shater/recommendations?page=1&pageSize=50', { admin: true }).catch(() => ({ data: [], total: 0 })),
    apiGet<PageData<ReportItem>>('/api/admin/min-shater/reports?page=1&pageSize=50', { admin: true }).catch(() => ({ data: [], total: 0 })),
    apiGet<Analytics>('/api/admin/min-shater/analytics', { admin: true }).catch(() => ({ requests: 0, pendingRequests: 0, approvedRequests: 0, closedRequests: 0, recommendations: 0, pendingRecommendations: 0, reports: 0, zeroRecommendation: 0 })),
  ]);
  return <section>
    <div className="sectionHead"><div><span className="eyebrow">المجتمع</span><h1 className="pageTitle">مين شاطر؟</h1></div><span className="badge">مركز المراجعة</span></div>
    <p className="pageLead">أسئلة الناس وترشيحاتهم تمر بالمراجعة قبل الظهور العام، مع الاحتفاظ بدورة الحالة وسجل القرارات.</p>
    <section className="statsGrid">{[['الأسئلة', analytics.requests ?? requests.total], ['معلّق الأسئلة', analytics.pendingRequests ?? 0], ['الترشيحات', analytics.recommendations ?? recommendations.total], ['البلاغات المعلقة', analytics.reports ?? 0]].map(([label, value]) => <article className="surface stat" key={label as string}><small>{label}</small><strong>{value}</strong><span>بيانات مباشرة</span></article>)}</section>
    <section className="section surface table"><div className="sectionHead"><h2>الأسئلة</h2><span className="badge">{requests.total}</span></div>{requests.data.length === 0 ? <p className="empty">لا توجد أسئلة.</p> : <table><thead><tr><th>السؤال</th><th>صاحب السؤال</th><th>التصنيف</th><th>الحالة</th><th>القرار</th></tr></thead><tbody>{requests.data.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><br /><small>{item.area?.name ?? 'كل قنا'} · {item._count?.recommendations ?? 0} ترشيح</small></td><td>{item.user?.name ?? '—'}</td><td>{item.category?.name ?? '—'}</td><td><span className="badge">{statusLabel[item.moderationStatus] ?? item.moderationStatus}</span></td><td><div className="actionRow"><form action={moderateMinShaterRequest}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="status" value="APPROVED" /><button className="approveButton" type="submit">اعتماد</button></form><form action={moderateMinShaterRequest}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="status" value="REJECTED" /><input type="hidden" name="reason" value="يرجى مراجعة محتوى السؤال" /><button className="rejectButton" type="submit">رفض</button></form></div></td></tr>)}</tbody></table>}</section>
    <section className="section surface table"><div className="sectionHead"><h2>الترشيحات</h2><span className="badge">{recommendations.total}</span></div>{recommendations.data.length === 0 ? <p className="empty">لا توجد ترشيحات.</p> : <table><thead><tr><th>الترشيح</th><th>السؤال</th><th>المساهم</th><th>الحالة</th><th>القرار</th></tr></thead><tbody>{recommendations.data.map((item) => <tr key={item.id}><td><strong>{item.provider?.name ?? item.recommendedName ?? 'ترشيح يدوي'}</strong><br /><small>{item.description ?? 'بدون تفاصيل'}</small></td><td>{item.request?.title ?? '—'}</td><td>{item.user?.name ?? '—'}</td><td><span className="badge">{statusLabel[item.moderationStatus] ?? item.moderationStatus}</span></td><td><div className="actionRow"><form action={moderateMinShaterRecommendation}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="status" value="APPROVED" /><button className="approveButton" type="submit">اعتماد</button></form><form action={moderateMinShaterRecommendation}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="status" value="REJECTED" /><input type="hidden" name="reason" value="يرجى مراجعة بيانات الترشيح" /><button className="rejectButton" type="submit">رفض</button></form></div></td></tr>)}</tbody></table>}</section>
    <section className="section surface table"><div className="sectionHead"><h2>البلاغات</h2><span className="badge">{reports.total}</span></div>{reports.data.length === 0 ? <p className="empty">لا توجد بلاغات.</p> : <table><thead><tr><th>الهدف</th><th>السبب</th><th>المبلّغ</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{reports.data.map((item) => <tr key={item.id}><td>{item.request?.title ?? item.recommendation?.provider?.name ?? item.recommendation?.recommendedName ?? '—'}</td><td>{item.reason}</td><td>{item.reporter?.name ?? '—'}</td><td><span className="badge">{statusLabel[item.status] ?? item.status}</span></td><td><div className="actionRow"><form action={moderateMinShaterReport}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="status" value="RESOLVED" /><button className="approveButton" type="submit">حل</button></form><form action={moderateMinShaterReport}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="status" value="DISMISSED" /><button className="rejectButton" type="submit">استبعاد</button></form></div></td></tr>)}</tbody></table>}</section>
  </section>;
}
